### ISSUE TITLE
Spacetime appears to ignore timezone when parsing ISO times

### ISSUE THREAD

**Issue by samtgarson** [smallwins/spacetime#33] opened 2017-12-07 16:13 UTC
```js
const timestamp = '2017-04-03T08:00:00-0700'
const s = spacetime(timestamp)
const date = new Date(timestamp)

s.timezone().name
// "Europe/London"

s.hour()
// 8 

date.getUTCHours()
// 15 
```

Unless I'm missing something in how spacetime is supposed to be used, I can't see a way of telling the library that a) the date was in a different timezone to me or b) to somehow localize the datetime I gave it.

It appears [here](https://github.com/smallwins/spacetime/blob/master/src/input/strParse.js#L24-L32) that you match for a timezone but then don't do anything with it (it would be `arr[5]`).

I'm happy to put in a PR but I wanted to check I wasn't misunderstanding what this library is supposed to do.

**Comment by spencermountain** [comment] 2017-12-08 16:16
hey Sam, yeah i think I see what you mean.
if i can remember, i started parsing the timestamp, ran into the timezone, and thought, hmm should this over-ride a timezone entered as the second param? Then i thought, how should we guess which timezone it is, given the offset? then i thought, man, it's almost lunch time.

so yeah, my bad ;)

if you pass a iana timezone in the second param, you should get your expected behaviour I believe.
would be happy to merge any solution to handling this. up to you!
cheers

**Comment by spencermountain** [comment] 2017-12-08 16:23
hey, maybe this?:
we add `UTC-7`, and so forth, to [the zonefile](https://github.com/smallwins/spacetime/blob/master/data/zonefile.2017.json), which have no dst changes.
if we get a `-0700` suffix on the timestamp, we overwrite (any?) given timezone as second param, ... unless it's ...currently the same offset?

worse is the condition when you say `spacetime('xxx--0700', 'Europe/London')` - because then it's a double-conversion. I suppose we could try to support that - ie find x-oclock in 7-offset, then find out what time that is in london.
yikes!
(just thinking aloud)

**Comment by samtgarson** [comment] 2017-12-15 14:19
I believe the ISO date format (with timezone) is an absolute timestamp, not a relative one—i.e. the offset is always the offset from GMT, not relative to your current timezone.

If that's true, then I believe the two ways of specifying the timezone should be mutually exclusive, and I believe the ISO offset should take precedence.

If both are given, I see no issue with ignoring the second argument (you could also log a warning).

I believe this is also very easy to understand for users of this library, and it makes it compatible with anyone who is working with dates from an API (like I am) which include timezone in the timestamp.

I don't know the library well enough to suggest how this should be suggested, but if you agree I might be able to take a look at putting a PR in... 👍

**Comment by ryanblock** [comment] 2017-12-15 17:11
Couple points of clarification: ISO 8601 defines a broad standard for representation of dates, not a single standard.

Additionally, I believe offsets are relative to UTC, not GMT. (They are often the same, but slightly different.)

**Comment by samtgarson** [comment] 2017-12-16 15:56
Of course, my bad about GMT ≠ UTC, I get lazy being in the UK...

Regardless of the broad standard, I still believe the absolute offset is the easiest way to work with timezones if you'd like to accept the format which includes a timezone offset in the timestamp? Although open to other suggestions of course 😊

**Comment by spencermountain** [comment] 2018-02-01 18:10
hey, got this working and I'm somewhat happy with it - atleast it didn't destroy any passing-tests.

[this look alright](https://github.com/smallwins/spacetime/blob/8e587df5e986b471318ddb1a384221ba1aa317af/test/utcOffset.test.js)? 
will be in v3.0

**Comment by samtgarson** [comment] 2018-02-02 09:46
@spencermountain LGTM! Out of curiosity, are you going with ignoring the second argument if the first has a timezone included? Or has the API changed in 3.0?

Thanks for this, going to be really helpful!

**Comment by spencermountain** [comment] 2018-02-02 15:03
hey yeah, it would ignore the 2nd argument if it's there.
I thought about adding a warning message if that's the case. Maybe I should do that today.

**Comment by spencermountain** [comment] 2018-02-02 15:15
yeah, new console.warn behaviour in the next release:
```js
const s = spacetime('2017-04-03T08:00:00-0700', 'Canada/Eastern')
/*  - Setting timezone to: 'Etc/GMT-7'
     from ISO string '-0700'
     overwriting given timezone: 'Canada/Eastern'*/
```
what do you think Sam?

**Comment by samtgarson** [comment] 2018-03-01 13:41
Can see this has been released—thanks! Should this be closed?

**Closed** 2018-03-01 14:34 UTC

**Comment by flintjohnston** [comment] 2018-10-10 19:01
I think I'm still seeing this bug.

> let item = new Date()
> let timeStr = item.toString()
> timeStr = timeStr.slice(0, timeStr.indexOf(' ('))
> let tz = timeStr.slice(-5)
> timeStr = item.toISOString().replace('Z', tz)
> let timeST = spacetime(timeStr)
> console.log(timeST.timezone())
> // 'America/Los_Angeles' <= expected tz
> console.log(timeST.time())
> // time returned is off by 7 hours, or my GMT offset
